"""Utilidades puras del arañador audiovisual.

La API se mantiene deliberadamente sin dependencias de red para que pueda
usarse desde pruebas, arañas y procesos por lotes.
"""

from .generador_hash import (
    calcular_hash_contenido,
    calcular_hash_url,
    calcular_sha256_contenido,
    calcular_sha256_url,
    generar_hash_contenido,
    generar_hash_url,
    hash_contenido,
    hash_texto,
    hash_url,
    normalizar_contenido_para_hash,
)
from .normalizador_url import (
    PARAMETROS_TRACKING,
    SUFFIXES_LOCALES,
    SUFIJOS_PUBLICOS_LOCALES,
    canonicalizar_url,
    dominio_registrable,
    es_url_http,
    extraer_dominio,
    extraer_dominio_registrable,
    normalizar_url,
    obtener_dominio,
    obtener_dominio_registrable,
    obtener_host_origen,
)
from .rutas import (
    construir_ruta_particionada,
    crear_ruta_particionada,
    crear_ruta_segura,
    crear_slug,
    generar_ruta_particionada,
    generar_slug,
    obtener_raiz_datos,
    particion_hash,
    particionar_hash,
    particiones_hash,
    resolver_ruta_datos,
    ruta_particionada,
    ruta_segura,
    slug,
    slugify,
)

__all__ = [
    "PARAMETROS_TRACKING",
    "SUFIJOS_PUBLICOS_LOCALES",
    "SUFFIXES_LOCALES",
    "calcular_hash_contenido",
    "calcular_hash_url",
    "calcular_sha256_contenido",
    "calcular_sha256_url",
    "canonicalizar_url",
    "construir_ruta_particionada",
    "crear_ruta_particionada",
    "crear_ruta_segura",
    "crear_slug",
    "dominio_registrable",
    "generar_ruta_particionada",
    "generar_slug",
    "es_url_http",
    "extraer_dominio",
    "extraer_dominio_registrable",
    "generar_hash_contenido",
    "generar_hash_url",
    "hash_contenido",
    "hash_url",
    "hash_texto",
    "normalizar_contenido_para_hash",
    "normalizar_url",
    "obtener_dominio",
    "obtener_raiz_datos",
    "obtener_dominio_registrable",
    "obtener_host_origen",
    "particiones_hash",
    "particion_hash",
    "particionar_hash",
    "resolver_ruta_datos",
    "ruta_particionada",
    "ruta_segura",
    "slug",
    "slugify",
]
